services:
  - type: web
    name: lovie-p2p-payment-api
    runtime: docker
    dockerfilePath: ./Dockerfile.api
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SSL
        value: "true"
      - key: CORS_ORIGIN
        sync: false
      - key: APP_BASE_URL
        sync: false
